#!/usr/bin/env bash

# ----------------------------------------------------
# file:     $HOME/scripts/abook-import-aliases
# author    Armin Wolfermann
# ----------------------------------------------------

abook --convert --informat mutt --infile $HOME/.mutt/aliases \
			--outformat abook --outfile $HOME/.abook/addressbook.new
mv $HOME/.abook/addressbook $HOME/.abook/addressbook.bak
mv $HOME/.abook/addressbook.new $HOME/.abook/addressbook
