#!/bin/bash

mount_point="/media"
share="//sv005/share"
domain="TOSCA7"
user="sjors"
pass=$(exec python2 -c "import keyring; print keyring.get_password('gmail', 'jls')")

sudo mount.cifs $share $mount_point -o username=$user,password=$pass,domain=$domain,iocharset=utf8,file_mode=0777,dir_mode=0777
