#!/bin/bash

# ----------------------------------------------------
# file:     $HOME/scripts/auto-mount
# author    jls - http://sjorssparreboom.nl
# ----------------------------------------------------

# mounting script for home share

mount_point="/media"
share="//sv005/share"
domain="TOSCA7"
user="sjors"
pass=$(pass show jlssparreboom@gmail.com)

sudo mount.cifs "$share" "$mount_point" -o username="$user",password="$pass",domain="$domain",iocharset=utf8,file_mode=0777,dir_mode=0777

# vim:nu:ai:noet:sts=8:sw=8:ts=8:
