#!/bin/bash

# Used for outputting battery level

interface="BAT0"
batt="/sys/class/power_supply/${interface}"

current=$(<"${batt}"/charge_now)
full=$(<"${batt}"/charge_full)
state=$(<"${batt}"/status)

charge=$(( current * 100 / full ))

case "${state}" in
  Full) batstat="=" ;;
  Charging) batstat="+" ;;
  Discharging) batstat="-" ;;
esac

printf '%s\n' "${batstat}${charge}%"

# vim:set ft=sh et sw=2 ts=2 tw=79:
