#! /usr/bin/env/sh

mail_dirs="${HOME}/Documents/Mail/*/Inbox/new"
mail="$(find $mail_dirs -type f | wc -l)"

if (( $mail == 0 )); then
  printf "0"
else
  printf "%b" $mail
fi

# vim:set ft=sh et sw=2 ts=2 tw=79:
