#!/bin/bash

# ----------------------------------------------------
# file:     $HOME/scripts/connection
# author    Jason W Ryan
# ----------------------------------------------------

# Used for outputting status of wireless adapter to the dwm status bar

interface="wlp2s0"
sys_dir="/sys/class/net/${interface}"

con=$(<${sys_dir}/operstate)

echo -e "NET\x04${con^^}\x01"
