#!/bin/bash

profile=$(netctl list | sed -n '/*/p' | sed -n 's/\*//gp')
device=$(echo $profile | cut -d - -f1 | tr -d ' ')
carrier=$(</sys/class/net/${device}/carrier)

if [[ $profile != "" ]]; then
  case "${carrier}" in
    1) network="CONNECTION: UP | ACCESS POINT: ${profile}" ;;
    *) network="CONNECTION: DOWN | ACCESS POINT: ${profile}" ;;
  esac
else
  case "${carrier}" in
    1) network="CONNECTION: UP | ACCESS POINT: DISCONNECTED" ;;
    *) network="CONNECTION: DOWN | ACCESS POINT: DISCONNECTED" ;;
  esac
fi

printf "%s\n" "${network}"
