#! /bin/sh

DAWN_TIME=$(( 8 * 60 ))
DUSK_TIME=$(( 20 * 60 ))

hours=$(date +%H)
minutes=$(date +%M)
total=$(( ${hours#0} * 60 + ${minutes#0} ))

if (( $total < $DUSK_TIME)) && (( $total < $DAWN_TIME )); then
  # night configuration
  dmenu_run -nb "#0b141a" -nf "#61707a" -sf "#61707a" -sf "#ba656d" -sb "#0b141a"
elif (( $total >= $DAWN_TIME )) && (( $total < $DUSK_TIME )); then
  # day configuration
  dmenu_run -nb "#ffffff" -nf "#6d767d" -sf "#6d767d" -sf "#a69500" -sb "#ffffff"
else
  # night configuration
  dmenu_run -nb "#0b141a" -nf "#61707a" -sf "#61707a" -sf "#ba656d" -sb "#0b141a"
fi

# vim:set ft=sh et sw=2 ts=2 tw=79:
