#! /bin/bash

# we have to find the dotfiles directory
scripts_dir="$(realpath $(dirname ${BASH_SOURCE}))"
machine_dir="$(realpath $(dirname $scripts_dir))"
dotfiles=$(find $machine_dir -maxdepth 1 -type d -name "*dotfiles")
buildfiles=$(find $machine_dir -maxdepth 1 -type d -name "*builds")

old_dotfiles="${HOME}/.dotfiles_old"
files="${dotfiles}/install"

mkdir $dotfiles &> /dev/null
mkdir $old_dotfiles &> /dev/null

while read line; do
  comment=$(echo $line | awk '{ if (/^#/) { print "0" } else { print "1"} }')
  empty=$(echo $line | awk '{ if (/./) { print "1" } else { print "0" } }')
  if (( $comment == 1 )) && (( $empty == 1 )); then
    file=$line
    stripped_file=$(echo $file | sed -e 's/^.*\///')
    yes | rm -rf  "${old_dotfiles}/.*" && yes | rm -rf "${old_dotfiles}/*"
    mv "${HOME}/.${stripped_file}" "${old_dotfiles}" &> /dev/null
    ln -s "${dotfiles}/${file}" "${HOME}/.${stripped_file}"
  fi
done < $files

# zsh config stuff
if (hash zsh &>/dev/null); then
  mkdir -p "${DOTFILES}/zsh/history" &> /dev/null
  touch "${DOTFILES}/zsh/history/histfile"
  # setup correct paths for configs in zshenv
  sed -i "s#DOTFILES=.*#DOTFILES=\"${dotfiles}\"#g" "${dotfiles}/zsh/zshenv"
  sed -i "s#SCRIPTS=.*#SCRIPTS=\"${scripts_dir}\"#g" "${dotfiles}/zsh/zshenv"
  sed -i "s#BUILDS=.*#BUILDS=\"${buildfiles}\"#g" "${dotfiles}/zsh/zshenv"
else
  printf "%s\n" "Zsh was not found on your computer, please install!"
fi

# vim config stuff
mkdir -p "${DOTFILES}/vim/backup" &> /dev/null
mkdir -p "${DOTFILES}/vim/autoload" &> /dev/null
if [[ ! -f "${DOTFILES}/vim/autoload/plug.vim" ]]; then
  curl -o "${DOTFILES}/vim/autoload/plug.vim" https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# vim:set ft=sh et sw=2 ts=2 tw=79:
