#!/usr/bin/env bash
# based on: https://github.com/cdown/passmenu

shopt -s nullglob globstar

prefix=${PASSWORD_STORE_DIR:-~/.password-store}
files=( "$prefix"/**/**.gpg )
files=( "$prefix"/**/*.gpg )
files=( "${files[@]#"$prefix"/}" )
files=( "${files[@]%.gpg}" )
fbase=( "${files[@]##*/}" )

word=$(printf '%s\n' "${fbase[@]}" | dmenu -i -p "Passes:" -fn "Cousine:size=10" -nb "#303030" -nf "#ffffff" -sb "#303030" -sf "#decc94" "$@")

if [[ -n $word ]]; then
  for match in "${files[@]}"; do 
    if [[ $word == ${match#*/} ]]; then
      /usr/bin/pass show -c "$match" 2>/dev/null
    fi
  done
fi
