#! /bin/sh

# Modified version of Jason W Ryan's dpass script

# based on: https://github.com/cdown/passmenu

shopt -s nullglob globstar

prefix=${PASSWORD_STORE_DIR:-~/.password-store}
files=( "$prefix"/**/**.gpg )
files=( "$prefix"/**/*.gpg )
files=( "${files[@]#"$prefix"/}" )
files=( "${files[@]%.gpg}" )
fbase=( "${files[@]##*/}" )

# word=$(printf '%s\n' "${fbase[@]}" | dmenu -i -p "Passes:" "$@")
word=$(printf '%s\n' "${fbase[@]}" | dmenu -fn "meslo:size=12" -nb "#282828" -nf "#ebdbb2" -sb "#282828" -sf "#cc241d" -i -p "Passes:" "$@")

if [[ -n $word ]]; then
  for match in "${files[@]}"; do 
    if [[ $word == ${match#*/} ]]; then
      /usr/bin/pass show -c "$match" 2>/dev/null
    fi
  done
fi
