#! /bin/sh

# Modified version of Jason W Ryan's dpass script

# based on: https://github.com/cdown/passmenu

shopt -s nullglob globstar

prefix=${PASSWORD_STORE_DIR:-~/.password-store}
files=( "$prefix"/**/**.gpg )
files=( "$prefix"/**/*.gpg )
files=( "${files[@]#"$prefix"/}" )
files=( "${files[@]%.gpg}" )
fbase=( "${files[@]##*/}" )

day_time=$(dusk-or-dawn)

if [[ $day_time == "dawn" ]]; then
  # day
  word=$(printf '%s\n' "${fbase[@]}" | dmenu -nb "#ffffff" -nf "#6d767d" -sf \
    "#6d767d" -sf "#a69500" -sb "#ffffff" -i -p "Passes:" "$@")
else
  word=$(printf '%s\n' "${fbase[@]}" | dmenu -nb "#0b141a" -nf "#61707a" -sf \
    "#61707a" -sf "#ba656d" -sb "#0b141a" -i -p "Passes:" "$@")
fi

if [[ -n $word ]]; then
  for match in "${files[@]}"; do
    if [[ $word == ${match#*/} ]]; then
      /usr/bin/pass -c "$match" 2>/dev/null
    fi
  done
fi

# vim:set ft=sh et sw=2 ts=2 tw=79:
