#!/usr/bin/env bash
# Status script for dwm

# Copyright (c) 2013-2015 Jason W Ryan
# The MIT License (MIT) http://opensource.org/licenses/MIT

# colours: 01:normal 02:white 03:red 04:green 05:yellow 06:blue
# 07:cyan 08:magenta 09:grey


music(){
    track="$(mpc current)"
    artist="${track%%- *}"
    title="${track##*- }"
    if [[ -n "$artist" ]]; then
        printf "%b" "\x08$artist\x01\x06$title\x01 •"
    fi
}

mbt(){
    tmp="$(awk '/^MB/ {print +$3}' <(sensors))"
    if (( tmp < 45 )); then
        printf "%b" "MB \x07$tmp\x01"
    else
        printf "%b" "\x03MB $tmp\x01"
    fi
}

gpu(){
    tmp="$(awk 'NR>1{exit};1' <(nvidia-settings -q gpucoretemp -t))"
    printf "%b" "GPU \x06$tmp\x01"
}

mem(){
    mem="$(awk '/^Mem/ {print $3}' <(free -m))"
    printf "%b" "\x04$mem\x01"
}

   # CPU line courtesy Procyon:
   # https://bbs.archlinux.org/viewtopic.php?pid=874333#p874333
cpu(){
    read cpu a b c previdle rest < /proc/stat
    prevtotal=$((a+b+c+previdle))
    sleep 0.5
    read cpu a b c idle rest < /proc/stat
    total=$((a+b+c+idle))
    cpu="$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))"
    printf "%b" "\x05$cpu%\x01"
}

hdd(){
    hd=( $(awk '
        {i=$5} /boot/ {a=i}; /root/ {b=i}; /home/ {c=i}; /media/ {d=i}
            END {print (NR>=11) ? a" "b" "c" "d : a" "b" "c}
        ' <(df -P)) )
    drives="${#hd[@]}"
    if (( drives > 3 )); then
        printf "%b " "\x08${hd[@]:0:3} \x06${hd[@]:3:1}\x01"
    else
        printf "%b " "\x08${hd[@]}\x01"
    fi
}

eml(){
    maildirs="$HOME/.mail/*/inbox/new/"
    ml="$(find $maildirs -type f | wc -l)"
    if (( ml > 0 )); then
        printf "%b" "\x03$ml\x01"
    else
        printf "0"
    fi
}

pac(){
    pup="$(pacman -Qqu --dbpath /tmp/checkup-db-jls/ | wc -l)"
    if (( pup > 0 )); then
        printf "%b" "\x05$pup\x01"
    else
        printf "0"
    fi
}

ups(){
    ups="$(wc -l </tmp/aurupdates*)"
    if (( ups > 0 )); then
        printf "%b" "\x05$ups\x01"
    else
        printf "0"
    fi
}

aur(){
    aur="$(awk '$0 !~ /^No /' /tmp/aurphans* | wc -l)"
    if (( aur > 0 )); then
        printf "%b" "\x03 ∆\x01"
    fi
}

con(){
    lan="$("$HOME/scripts/connection")"
    printf "%b" "$lan"
}

int(){
    int="$("$HOME/scripts/speed")"
    printf "%b" "$int"
}

bat(){
    bat="$("$HOME/scripts/batt")"
    printf "%b" "$bat"
}

weather(){
    temps="$(shaman -l Rotterdam,NL -m -c $HOME/.shaman/cache.json -f "%t" | awk '{printf "%i°C", $0}')"
    printf "%b" "\x05$temps\x01"
}

dte(){
    dte="$(date "+%H:%M")"
    printf "%b" "\x02$dte\x01"
}

# Pipe to status bar
xsetroot -name "$(music) • $(bat) • CPU $(cpu) MEM $(mem) • HDD $(hdd)\
• EML $(eml) • $(con) • $(weather) • $(dte) "
