#!/usr/bin/env sh

# ----------------------------------------------------
# file:     $HOME/scripts/dwm-start
# author    Jason W Ryan
# ----------------------------------------------------

# Script to start dwm in loop
# ----------------------------------------------------
while true; do
	$HOME/scripts/dwm-status
	sleep 2
done &

while true; do
	/usr/bin/dwm > /dev/null
	# /usr/bin/dwm 2> ~/builds/dwm/dwm.log # Log stderrors to file
done

# vim:nu:ai:noet:sts=8:sw=8:ts=8:
