#! /bin/sh
# ----------------------------------------------------
# file:   $HOME/scripts/dwm-start
# author: jls - http://sjorssparreboom.nl
# ----------------------------------------------------
while true; do
  /usr/bin/dwm > /dev/null
done
