#!/usr/bin/env sh

# Script to start dwm in loop
# ----------------------------------------------------


while true; do
    $HOME/scripts/dwm-status
    sleep 2
done &

while true; do
    /usr/bin/dwm > /dev/null
    # to log stderrors to a file
    # ----------------------------------------------------
    #/usr/bin/dwm 2> ~/build/dwm/dwm.log
done
