#!/usr/bin/env bash

# ----------------------------------------------------
# file:     $HOME/scripts/dwm-status
# author    jls - http://sjorssparreboom.nl
# ----------------------------------------------------

# Modified version of Jason W Ryan's dwm-status script

# Status script for dwm

# The MIT License (MIT) http://opensource.org/licenses/MIT

music() {
	track="$(mpc current)"
	artist="${track%%- *}"
	title="${track##*- }"
	if [[ -n "$artist" ]]; then
		printf "%b" "\x06$artist\x01\x06- $title\x01"
	else
		printf "%b" "\x04N/A\x01"
	fi
}

gpu() {
	tmp="$(awk 'NR>1{exit};1' <(nvidia-settings -q gpucoretemp -t))"
	printf "%b" "GPU \x06$tmp\x01"
}

mem() {
	mem="$(awk '/^Mem/ {print $3}' <(free -m))"
	printf "%b" "\x04$mem\x01"
}

# CPU line courtesy Procyon:
# https://bbs.archlinux.org/viewtopic.php?pid=874333#p874333
cpu() {
	read cpu a b c previdle rest < /proc/stat
	prevtotal=$((a+b+c+previdle))
	sleep 0.5
	read cpu a b c idle rest < /proc/stat
	total=$((a+b+c+idle))
	cpu="$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))"
	printf "%b" "\x05$cpu%\x01"
}

hdd() {
	hd=$(df -h |  awk '/\/dev\/sda/ {sum +=$5+0} END {print sum}')
	if [[ -z "$hd" ]]; then
		printf "%b" "\x05"N/A"\x01"
	else
		printf "%b" "\x05${hd}%\x01"
	fi
}

eml() {
	maildirs="$HOME/.mail/*/inbox/new/"
	ml="$(find $maildirs -type f | wc -l)"
	if (( ml > 0 )); then
		printf "%b" "\x03$ml\x01"
	else
		printf " 0 "
	fi
}

pac() {
	pup="$(pacman -Qqu --dbpath /tmp/checkup-db-${USER}/ | wc -l)"
	if (( pup > 0 )); then
		printf "%b" "\x05$pup\x01"
	else
		printf " 0"
	fi
}

ups() {
	ups="$(wc -l < /tmp/aurupdates*)"
	if (( ups > 0 )); then
		printf "%b" "\x05$ups\x01"
	else
		printf " 0 "
	fi
}

aur() {
	aur="$(awk '$0 !~ /^No /' /tmp/aurphans* | wc -l)"
	if (( aur > 0 )); then
		printf "%b" "\x03∆\x01"
	fi
}

# Needs my soundctl http://github.com/git-jls/scripts/blob/master/soundctl script added to $PATH
vol() {
	lvl=$(soundctl volume | awk 'BEGIN {IGNORECASE=1} /running/ {getline;getline; print $2}')
	if [[ -z "$lvl" ]]; then
		printf "%b" "\x030%\x01"
	else
		printf "%b" "\x03$lvl\x01"
	fi
}

con() {
	lan="$("$HOME/scripts/connection")"
	printf "%b" "$lan"
}

int() {
	int="$("$HOME/scripts/speed")"
	printf "%b" "$int"
}

bat() {
	bat="$("$HOME/scripts/batt")"
	printf "%b" "$bat"
}

weather() {
	temps="$(shaman -l Rotterdam,NL -m -c $HOME/.shaman/cache.json -f "%t" | awk '{printf "%i°C", $0}')"
	printf "%b" "\x05$temps\x01"
}

dte() {
	dte="$(date "+%H:%M")"
	printf "%b" "\x02$dte\x01"
}

# Pipe to status bar
xsetroot -name "♫ $(music)♦ VOL$(vol)♦ $(bat)♦ MEM$(mem)CPU$(cpu)♦ HDD$(hdd)♦ EML$(eml)♦ PKG$(pac) AUR$(ups)$(aur)♦ $(con)♦$(weather)♦$(dte)"
