#! /bin/sh

DAWN_TIME=$(( 8 * 60 ))
DUSK_TIME=$(( 20 * 60 ))

minutes=$(( $(date +%H) * 60 + $(date +%M) ))

if (( $minutes < $DUSK_TIME)) && (( $minutes < $DAWN_TIME )); then
  # night configuration
  dmenu_run -nb "#0b141a" -nf "#61707a" -sf "#61707a" -sf "#ba656d" -sb "#0b141a"
elif (( $minutes >= $DAWN_TIME )) && (( $minutes < $DUSK_TIME )); then
  # day configuration
  dmenu_run -nb "#ffffff" -nf "#6d767d" -sf "#6d767d" -sf "#a69500" -sb "#ffffff"
else
  # night configuration
  dmenu_run -nb "#0b141a" -nf "#61707a" -sf "#61707a" -sf "#ba656d" -sb "#0b141a"
fi
