#!/usr/bin/env bash

shopt -s nullglob globstar

prefix=${PASSWORD_STORE_DIR:-~/.password-store}
files=( "$prefix"/**/**.gpg )
files=( "$prefix"/**/*.gpg )
files=( "${files[@]#"$prefix"/}" )
files=( "${files[@]%.gpg}" )
fbase=( "${files[@]##*/}" )

for match in "${files[@]}"; do
    printf "%-10s %20s" $match 
    /usr/bin/pass show "$match" 2>/dev/null
done
