#! /bin/sh

shopt -s nullglob globstar

prefix=${PASSWORD_STORE_DIR:-~/.password-store}

for file in "$prefix"/**/*.gpg; do
  file="${file#$prefix/}"
  printf "%s\t" "Name: ${file%.*}"
  pass "${file%.*}"
  printf "\n\n"
done | column -t
