#!/usr/bin/env bash
# ----------------------------------------------------
# file:     $HOME/go-setup.sh
# author    jls - http://sjorssparreboom.nl
# vim:nu:ai:si:et:ts=4:sw=4:fdm=indent:fdn=1:ft=sh:
# ----------------------------------------------------


if [ ! -n "${GOPATH+1}" ]; then
    printf "Set your GOPATH!\n";
    exit 0
fi
# set version number
# ----------------------------------------------------
VERSION=1.0
FILENAME="go-setup"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# colours
# ----------------------------------------------------
lt=$'\e[1;36m' # light cyan
dk=$'\e[0;36m' # dark cyan
tx=$'\e[1;32m' # green text
mg=$'\e[1;35m' # magenta text
ec=$'\e[0m'

# ASCII goodness…
# ----------------------------------------------------
logo() {
cat <<- EOF

${lt}                 +
                 #                 ${tx}
                ###                ${tx}
               #####               ${tx}
               ######              ${tx}
              ; #####;             ${tx}
             +##.#####             ${tx}
            +##########            ${tx}
           #############;          ${tx}
          ###############          ${tx}
         #######   #######         ${tx}
       .######;     ;#####\`.      ${tx}
      .#######;     ;#######.      ${tx}
      #########.   .########\`
     ######'           '######
    ;####                 ####;
    ##'                     '##
   #'                         \`#
  '                            \`${ec}
${mg}BUILD ON ARCH${ec}
${dk}Go project builder - ${mg}Version $VERSION${ec}
EOF
}
# help
# ----------------------------------------------------
help() {
cat <<- EOF
${mg}SYNOPSIS${ec}
${dk}$FILENAME -d <directory> -r <repository> ${ec}
${mg}OPTIONS${ec}
${dk}-h             Show this message${ec}
${dk}-d             Directory of the project${ec}
${dk}-r             Repository name${ec}
${dk}-v             Version${ec}
${mg}APPLICATION TYPES${ec}
${dk}console        Console Application${ec}
${mg}EXAMPLE${ec}
${dk}$FILENAME -d $GOPATH/MyGoApp -r github.com/your-name/repo ${ec}
EOF
}

# Create the directories
# ----------------------------------------------------
createDirs() {
    mkdir -p $GOPATH/$OPTARG/bin
    mkdir -p $GOPATH/$OPTARG/pkg
    mkdir -p $GOPATH/$OPTARG/src && touch $GOPATH/$OPTARG/src/.gitignore;
}

createRepoDir() {
    mkdir -p $GOPATH/src/$OPTARG
    cd $GOPATH/src/$OPTARG
    touch README.md && printf "%s \n" "$(date)" > README.md && printf "%s \n" "PROJECT DESCRIPTION:" >> README.md
    printf "%s \n" "Don't forget to manually initialize the repo! Goodbye!"
}

# show/check options
# ----------------------------------------------------
if [ $# -eq 0 ] ; then
    logo
    help
    exit 1;
fi
while getopts ":v:h:d:r:" opt
  do
    case "$opt" in
      "v")
        printf "${mg}Version $VERSION\n${ec}"
        exit 0;
        ;;
      "h")
        logo
        help
        exit 0;
        ;;
      "d")
        createDirs
        ;;
      "r")
        createRepoDir
        ;;
      "?")
        printf "Unknown option $OPTARG\n"
        exit 1;
        ;;
      ":")
        printf "No argument value for option $OPTARG\n"
        exit 1;
        ;;
        *)
        printf "Unknown error while processing options\n"
        exit 0;
        ;;
    esac
  done
shift $(($OPTIND - 1))
# Trap pid and request lock
# ----------------------------------------------------
LOCK_FILE=/tmp/${SUBJECT}.lock
if [ -f "$LOCK_FILE" ]; then
printf "Script is already running\n"
exit
fi
trap "rm -f $LOCK_FILE" EXIT
touch $LOCK_FILE 
