#!/usr/bin/env sh

# ! IMPORTANT !
# ----------------------------------------------------
# Before using this script check the output:foo for the output source on your device

# user details
USR_NAME=$(w -hs | awk 'NR==1 {print $1}')
USR_ID=$(id -u "$USR_NAME")

# cards
HDMI=$(pactl list cards short | awk 'NR==1 {print $2}')
ANALOG=$(pactl list cards short | awk 'NR==2 {print $2}')
HEADPHONE=$(pactl list cards short | awk 'NR==3 {print $2}')

# stats
HDMI_SINK_STAT=$(pactl list sinks short | awk '{ if(/hdmi/ || /HDMI/) { {print $7} ; } ; }')
HDMI_STAT=$(cat /sys/class/drm/card0/*HDMI*/status)

# sinks (to move)
CURRENT_SINK=$(pactl list sink-inputs short | awk 'NR==1 {print $1}')
HDMI_SINK=$(pactl list sinks short | awk '{ if(/hdmi/ || /HDMI/) { {print $2} ; } ; }')
ANALOG_SINK=$(pactl list sinks short | awk '{ if(/analog/ || /ANALOG/) { {print $2} ; } ; }')

export PULSE_SERVER="unix:/run/user/"$USR_ID"/pulse/native"

if [[ $HDMI_STAT == connected ]] && [[ $HDMI_SINK_STAT == SUSPENDED ]]; then
   sudo -u "$USR_NAME" pactl --server "$PULSE_SERVER" set-card-profile "$HDMI" output:hdmi-stereo-extra1
   sudo -u "$USR_NAME" pactl --server "$PULSE_SERVER" set-sink-volume "$HDMI_SINK" 25% # ! IMPORTANT
   [[ $CURRENT_SINK ]] && sudo -u "$USR_NAME" pactl --server "$PULSE_SERVER" move-sink-input "$CURRENT_SINK" "$HDMI_SINK"
else
   sudo -u "$USR_NAME" pactl --server "$PULSE_SERVER" set-card-profile "$ANALOG" output:analog-stereo+input:analog-stereo
   sudo -u "$USR_NAME" pactl --server "$PULSE_SERVER" set-sink-volume "$ANALOG_SINK" 25% # ! IMPORTANT
   [[ $CURRENT_SINK ]] && sudo -u "$USR_NAME" pactl --server "$PULSE_SERVER" move-sink-input "$CURRENT_SINK" "$ANALOG_SINK"
fi
