#!/usr/bin/env sh

while :; do
  wp=$($SCRIPTS/wallpaper | sed -r 's/(^|$)/\1"/g')
  eval "feh --randomize --bg-fill $wp"
  sleep 10
done &

while ((1)); do

  day_time=$(dusk-or-dawn)

  if [[ $day_time == "dawn" ]]; then
    # day
    cat $XDG_CONFIG_HOME/i3/config_day > $XDG_CONFIG_HOME/i3/config
    i3-msg -q reload
  else
    cat $XDG_CONFIG_HOME/i3/config_night > $XDG_CONFIG_HOME/i3/config
    i3-msg -q reload
  fi
  sleep 1
done &

/usr/bin/i3 &> /dev/null

# vim:set ft=sh et sw=2 ts=2 tw=79:
