#!/usr/bin/env sh

while :; do
  wp=$($SCRIPTS/wallpaper | sed -r 's/(^|$)/\1"/g')
  eval "feh --randomize --bg-fill $wp"
  sleep 10
done &

NIGHT=0
DAY=1

config=$NIGHT

while ((1)); do
  DAWN_TIME=$(( 8 * 60 ))
  DUSK_TIME=$(( 20 * 60 ))

  minutes=$(( $(date +%H) * 60 + $(date +%M) ))

  if (( $minutes < $DUSK_TIME)) && (( $minutes < $DAWN_TIME )); then
    # night configuration
    cat $XDG_CONFIG_HOME/i3/config_night > $XDG_CONFIG_HOME/i3/config
    (( $config != $NIGHT )) && i3-msg -q reload; config=$NIGHT
  elif (( $minutes >= $DAWN_TIME )) && (( $minutes < $DUSK_TIME )); then
    # day configuration
    cat $XDG_CONFIG_HOME/i3/config_day > $XDG_CONFIG_HOME/i3/config
    (( $config != $DAY )) && i3-msg -q reload; config=$DAY
  else
    # night configuration
    cat $XDG_CONFIG_HOME/i3/config_night > $XDG_CONFIG_HOME/i3/config
    (( $config != $NIGHT )) && i3-msg -q reload; config=$NIGHT
  fi
  sleep 1
done &

/usr/bin/i3 &> /dev/null
