#!/bin/sh

----------------------------------------------------
file:     $HOME/scripts/mailrun
author    Jason W Ryan
----------------------------------------------------


PID=$(pgrep offlineimap)

[ -n "$PID" ] && exit 1

/usr/bin/offlineimap -o -u quiet &>/dev/null &

/usr/bin/notmuch new

exit 0
