#!/usr/bin/env sh

# ----------------------------------------------------
# file:     $HOME/scripts/mailcheck
# author    Jason W Ryan
# ----------------------------------------------------


maildirs="$HOME/.mail/*/inbox/new/"
ml="$(find $maildirs -type f | wc -l)"
if [ $ml == 0 ]; then
	printf "0"
else
	printf "%b" "$ml"
fi
