#! /bin/sh

day_time=$(dusk-or-dawn)

if [[ $day_time == "dawn" ]]; then
  # day
  for a in ~/.mutt/accounts/*;
  do
    sed -i 's/night/day/g' "$a"
  done
  sed -i 's/night/day/g' ~/.mutt/muttrc
  sed -i 's/night/day/g' ~/.mutt/configs/sidebar.config
else
  # night
  for a in ~/.mutt/accounts/*;
  do
    sed -i 's/day/night/g' "$a"
  done
  sed -i 's/day/night/g' ~/.mutt/muttrc
  sed -i 's/day/night/g' ~/.mutt/configs/sidebar.config
fi

/usr/bin/mutt

# vim:set ft=sh et sw=2 ts=2 tw=79:
