#!/bin/bash
icon='/usr/share/icons/gnome/scalable/actions/media-playback-start-symbolic.svg'

line="$(ncmpcpp --now-playing '{%a - %t}|{%f}')"

notify-send -a ncmpcpp -t 5000 -i "${icon}" 'Now playing' "${line}"
