#! /bin/sh

day_time=$(dusk-or-dawn)

if [[ $day_time == "dawn" ]]; then
  sed -i 's/night/day/g' ${DOTFILES}/newsbeuter/config
else
  sed -i 's/day/night/g' ${DOTFILES}/newsbeuter/config
fi

/usr/bin/newsbeuter

# vim:set ft=sh  et sw=2 ts=2 tw=79:
