#! /bin/sh

day_time=$(dusk-or-dawn)

if [[ $day_time == "dawn" ]]; then
  # day
  newsbeuter -C ${DOTFILES}/newsbeuter/config_day
else
  # night
  newsbeuter -C ${DOTFILES}/newsbeuter/config_night
fi

# vim:set ft=sh  et sw=2 ts=2 tw=79:
