#!/bin/sh

# ----------------------------------------------------
# file:     $HOME/scripts/presentation
# author    jls - http://sjorssparreboom.nl
# ----------------------------------------------------

# impressive(presentation software) wrapper script.
if (( $# != 1 )); then
  printf "%s\n" "Need 1 argument to start the presentation." 1>&2
  exit 0
fi
impressive --supersample --cache persistent --cachefile ."${1%%.pdf}".impressive_cache --transition None --transtime 500 $1

# vim:nu:ai:noet:sts=8:sw=8:ts=8:
