#!/usr/bin/env bash

# ----------------------------------------------------
# file:     $HOME/scripts/printfile
# author    Jason W Ryan
# ----------------------------------------------------
# send file to printer

file=$1
lpr "$file" && echo "${file##*/} sent to printer" | dzen2 -p 3
