#!/usr/bin/env bash

ping -c 3 8.8.8.8 &>/dev/null

# check connection
# ----------------------------------------------------
if [[ $? -ne 0 ]]; then
    sudo netctl restart wlp2s0-Oudedijk3A03 &>/dev/null
elif [[ $? -ne 0 ]]; then
    sudo python $HOME/scripts/edu && sudo netctl restart eduroam &>/dev/null
fi
