#!/usr/bin/env bash
# Script to open browser instances in tabbed

# exec vimprobable2 -e $(</tmp/tabbed.xid) "$1" &
# exec vimb -e $(</tmp/tabbed.xid) "$1" &
#!/usr/bin/env bash
[[ -z $((xprop -id $(</tmp/tabbed.xid)) 2>/dev/null) ]] && tabbed -d > /tmp/tabbed.xid 
exec vimprobable2 -e $(</tmp/tabbed.xid) $( [[  "$1"  ]] && echo "$1") &
