#!/usr/bin/env bash
# Script to open browser instances in tabbed
[[ -z $((xprop -id $(</tmp/tabbed.xid)) 2>/dev/null) ]] && tabbed -d > /tmp/tabbed.xid
exec vimb -e $(</tmp/tabbed.xid) $( [[  "$1"  ]] && echo "$1") &
