#! /bin/sh

pictures="${HOME}/pictures/"

mkdir $pictures &> /dev/null
mkdir "${pictures}/avatars" &> /dev/null
mkdir "${pictures}/screenshots" &> /dev/null
mkdir "${pictures}/wallpapers" &> /dev/null

scrot "${pictures}/screenshots/%d-%m-%Y-%T-screenshot.png"
