#!/usr/bin/env bash

# ----------------------------------------------------
# file:     $HOME/scripts/screenie
# author    jls - http://sjorssparreboom.nl
# ----------------------------------------------------

scrot ~/pictures/screenshots/%d-%m-%Y-%T-screenshot.png

# vim:nu:ai:noet:sts=8:sw=8:ts=8:
