#!/usr/bin/env bash

# ----------------------------------------------------
# file:     $HOME/scripts/screenie
# author    jls - http://sjorssparreboom.nl
# ----------------------------------------------------

scrot ~/pictures/screenshots/%d-%m-%Y-%T-screenshot.png
