#!/usr/bin/env bash

while (( 1 )); do
    ibus=$(ibus engine 2> /dev/null)
    time=$(date +"%a %Y-%m-%d %H:%M")
    batt=$(batt)
    net=$(conn)
    printf "%s %s %s" "BATTERY: ${batt} |" "${net} |" "${time}"
    printf "\n"
    sleep 1
done
