#! /bin/bash

# we have to find the dotfiles directory
scripts_dir="$(realpath $(dirname ${BASH_SOURCE}))"
dotfiles="$(realpath $(dirname $scripts_dir))/*dotfiles"

old_dotfiles="${HOME}/.dotfiles_old"
files="${dotfiles}/track"

mkdir $dotfiles &> /dev/null
mkdir $old_dotfiles &> /dev/null

while read file; do
  stripped_file=$(echo $file | sed -e 's/^.*\///')
  yes | rm -rf  "${old_dotfiles}/.*"  && yes | rm -rf "${old_dotfiles}/*"
  mv "${HOME}/.${stripped_file}" "${old_dotfiles}" &> /dev/null
  ln -s "${dotfiles}/${file}" "${HOME}/.${stripped_file}"
done < $files

# Setup correct DOTFILE paths
export DOTFILES=${dotfiles}
sed -i "s/DOTFILES=.*/DOTFILES=\"${dotfiles}\"/" < ${HOME}/.zshenv
