#! /usr/bin/env bash

# script for syncing directories with PHILIPS 16GB CIRCLE USB on hotplug

target=( $(awk '/media\/PHILIPS/ {print $2}' /proc/mounts) )

directories=(Documents Pictures School)

if [[ -n $target ]]; then
  # make sure it is read-write mounted
  for dir in "${directories[@]}"; do
    rsync -rmza --delete "$dir" "$target"
  done
fi
