#! /bin/sh

day_time=$(dusk-or-dawn)

if [[ $day_time == "dawn" ]]; then
  # day
  termite -c $XDG_CONFIG_HOME/termite/config_day
else
  # night
  termite -c $XDG_CONFIG_HOME/termite/config_night
fi

# vim:set ft=sh et sw=2 ts=2 tw=79:
