#!/usr/bin/env bash

# ----------------------------------------------------
# file:     $HOME/scripts/tex2pdf
# author    jls - http://sjorssparreboom.nl
# ----------------------------------------------------

# NOTE: For this script to work your working directory has
# to include NO whitespaces!

# check for input
(( $# != 1 )) && printf "%s\n" "Please provide input!" && exit 1

filename=$(basename "$1")
extension=${filename##*.}
filename=${filename%.*}
output=trash

echo $filename
if [[ ! -d "$output" ]]; then
	texi2pdf --build-dir="$output" --tidy "$1"
else
	bibtex ${output}/*/pdf/build/${filename}.aux
	texi2pdf --build-dir="$output" --tidy "$1"
fi
