#!/usr/bin/env bash

# ----------------------------------------------------
# file:     $HOME/scripts/tex2pdf
# author    jls - http://sjorssparreboom.nl
# ----------------------------------------------------

# check for input
(( $# != 1 )) && printf "%s\n" "Please provide input!" && exit 1

name="${tex::-4}"
output=trash

if [[ ! -d garbage ]]; then
	texi2pdf --build-dir="$output" --tidy "$1"
else
	bibtex garbage/${name}.t2d/pdf/build/${name}.aux
	texi2pdf --build-dir="$output" --tidy "$1"
fi

# vim:nu:ai:noet:sts=8:sw=8:ts=8:
