#!/usr/bin/env bash

# ----------------------------------------------------
# file:     $HOME/scripts/tube
# author    jls - http://sjorssparreboom.nl
# ----------------------------------------------------

# Modified version of Jason W Ryans tube script

# pass link to mpv

# termite --title mpv --exec="sh -c 'nohup mpv --ytdl-format=best $1 >/dev/null'" &
urxvt -title mpv -e sh -c "mpv --ytdl-format=best $1" &
