#!/usr/bin/env bash

# ----------------------------------------------------
# file:     $HOME/scripts/usb-audio-fix
# author    jls - http://sjorssparreboom.nl
# ----------------------------------------------------

# Fix for the volume control of certain devices (external usb headphones)

sudo sed -i 's/^volume = merge$/volume = ignore\nvolume-limit = 0.01/' /usr/share/pulseaudio/alsa-mixer/paths/analog-output.conf.common
