#! /bin/sh

day_time=$(dusk-or-dawn)

if [[ $day_time == "dawn" ]]; then
  sed -i 's/night/day/g' "${XDG_CONFIG_HOME}/zathura/zathurarc"
else
  sed -i 's/day/night/g' "${XDG_CONFIG_HOME}/zathura/zathurarc"
fi

/usr/bin/zathura

# vim:set ft=sh et sw=2 ts=2 tw=79:
